# Generated by Django 2.2.5 on 2022-07-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='movie_images')),
                ('rating', models.FloatField()),
                ('cast', models.ManyToManyField(blank=True, null=True, to='people.Person')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='categories.Category')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='people.Person')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
